### PR TITLE
Feature/imu ros test

### PR DESCRIPTION
**Pull request by rikba**
Attempting IMU->Leica position sensor calibration (https://github.com/ethz-asl/oomact/issues/48).

Currently the example launch file `imu_leica.launch` crashes with the 

```
 ModuleLink(traj.McSensor->leica) resolves to used module but of wrong type!
```

I could trace back the error to https://github.com/ethz-asl/oomact/blob/master/oomact/include/aslam/calibration/model/Module.h#L270 where the method `ptrAs<Interface>()` returns `nullptr` for position sensor type. It resolves successfully with pose sensor type.

Any hints @HannesSommer ?

### CODE REVIEW

**Comment by rikba** [comment]
I'll move the disscussion to https://github.com/ethz-asl/oomact/issues/48 .

**Comment by HannesSommer** [comment]
Ah, I overlooked this issue -- my bad. 
You have a pure position sensor here. The system is missing an initialization strategy. The error tells you basically that just a bit too generic (at that place it asks for a position sensor). It knows how to initialize the trajectory from a pose but not from a pure position sensor.

If you have no vehicle constraints that binds the velocity to the attitude somehow I believe the vehicle attitude is irrelevant for the question. If so, what you probably need here is a pure position trajectory for the IMU, which at the same time should be considered a pure accelerometer (Gyros don't help here -- given the assumption above). Do you agree? @ZacharyTaylor ?

Then, what you search for is the position of the position sensor in the IMU frame.

OOMACT can do that but is missing:
* a pure position trajectory (ah, you started that already. I could probably help with his but not very fast)
* an initialization for the position traj (e.g. based on the position sensor).

Why closing it? Too much work?

Having said that, I'm afraid you won't get a good estimate unless you have quite a good IMU and little acceleration noise (e.g. a mechanical damper on the IMU)

Sorry again that I overlooked the missing attitude in.

**Comment by rikba** [comment]
Ok, I can keep trying ;)

**Comment by HannesSommer** [comment]
Ah, oh no. It is wrong what I just wrote. You still need to co estimate the attitude of the IMU, for which the gyros help again. Otherwise the accelerometers can not be interpreted correctly. So a pose trajectory for the IMU is good. The problem and the missing piece is the initialization of the pose trajectory. 
A good way would probably be to use an EKF to fuse the IMU and the position sensor to initialize the trajectory (based on some rough estimate of the translation between the sensors).

A simpler method with higher failure probability for convergence later would probably be something like using the position from the position sensor and the attitude from integrating the gyros.

**Pull request closed without merging**
